/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedConnectionsRouteImport } from './routes/_authed/connections'
import { Route as AuthedApiPlaygroundRouteImport } from './routes/_authed/api-playground'
import { Route as AuthedAccountRouteImport } from './routes/_authed/account'
import { Route as AuthedWorkflowsIndexRouteImport } from './routes/_authed/workflows.index'
import { Route as AuthedRunsIndexRouteImport } from './routes/_authed/runs.index'
import { Route as AuthedResourcesIndexRouteImport } from './routes/_authed/resources/index'
import { Route as AuthedWorkflowsWorkflowIdRouteImport } from './routes/_authed/workflows/$workflowId'
import { Route as AuthedResourcesR2RouteImport } from './routes/_authed/resources/r2'
import { Route as AuthedResourcesKvRouteImport } from './routes/_authed/resources/kv'
import { Route as AuthedResourcesEnvVarsRouteImport } from './routes/_authed/resources/env-vars'
import { Route as AuthedResourcesD1RouteImport } from './routes/_authed/resources/d1'
import { Route as AuthedWorkflowsWorkflowIdIndexRouteImport } from './routes/_authed/workflows/$workflowId.index'
import { Route as AuthedWorkflowsWorkflowIdRunsRouteImport } from './routes/_authed/workflows/$workflowId.runs'
import { Route as AuthedWorkflowsWorkflowIdDeploymentsRouteImport } from './routes/_authed/workflows/$workflowId.deployments'
import { Route as AuthedWorkflowsWorkflowIdCanvasRouteImport } from './routes/_authed/workflows/$workflowId.canvas'
import { Route as AuthedWorkflowsWorkflowIdRunsIndexRouteImport } from './routes/_authed/workflows/$workflowId.runs.index'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedConnectionsRoute = AuthedConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedApiPlaygroundRoute = AuthedApiPlaygroundRouteImport.update({
  id: '/api-playground',
  path: '/api-playground',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAccountRoute = AuthedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedWorkflowsIndexRoute = AuthedWorkflowsIndexRouteImport.update({
  id: '/workflows/',
  path: '/workflows/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRunsIndexRoute = AuthedRunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedResourcesIndexRoute = AuthedResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedWorkflowsWorkflowIdRoute =
  AuthedWorkflowsWorkflowIdRouteImport.update({
    id: '/workflows/$workflowId',
    path: '/workflows/$workflowId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedResourcesR2Route = AuthedResourcesR2RouteImport.update({
  id: '/resources/r2',
  path: '/resources/r2',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedResourcesKvRoute = AuthedResourcesKvRouteImport.update({
  id: '/resources/kv',
  path: '/resources/kv',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedResourcesEnvVarsRoute = AuthedResourcesEnvVarsRouteImport.update({
  id: '/resources/env-vars',
  path: '/resources/env-vars',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedResourcesD1Route = AuthedResourcesD1RouteImport.update({
  id: '/resources/d1',
  path: '/resources/d1',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedWorkflowsWorkflowIdIndexRoute =
  AuthedWorkflowsWorkflowIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedWorkflowsWorkflowIdRoute,
  } as any)
const AuthedWorkflowsWorkflowIdRunsRoute =
  AuthedWorkflowsWorkflowIdRunsRouteImport.update({
    id: '/runs',
    path: '/runs',
    getParentRoute: () => AuthedWorkflowsWorkflowIdRoute,
  } as any)
const AuthedWorkflowsWorkflowIdDeploymentsRoute =
  AuthedWorkflowsWorkflowIdDeploymentsRouteImport.update({
    id: '/deployments',
    path: '/deployments',
    getParentRoute: () => AuthedWorkflowsWorkflowIdRoute,
  } as any)
const AuthedWorkflowsWorkflowIdCanvasRoute =
  AuthedWorkflowsWorkflowIdCanvasRouteImport.update({
    id: '/canvas',
    path: '/canvas',
    getParentRoute: () => AuthedWorkflowsWorkflowIdRoute,
  } as any)
const AuthedWorkflowsWorkflowIdRunsIndexRoute =
  AuthedWorkflowsWorkflowIdRunsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedWorkflowsWorkflowIdRunsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/account': typeof AuthedAccountRoute
  '/api-playground': typeof AuthedApiPlaygroundRoute
  '/connections': typeof AuthedConnectionsRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/settings': typeof AuthedSettingsRoute
  '/resources/d1': typeof AuthedResourcesD1Route
  '/resources/env-vars': typeof AuthedResourcesEnvVarsRoute
  '/resources/kv': typeof AuthedResourcesKvRoute
  '/resources/r2': typeof AuthedResourcesR2Route
  '/workflows/$workflowId': typeof AuthedWorkflowsWorkflowIdRouteWithChildren
  '/resources/': typeof AuthedResourcesIndexRoute
  '/runs/': typeof AuthedRunsIndexRoute
  '/workflows/': typeof AuthedWorkflowsIndexRoute
  '/workflows/$workflowId/canvas': typeof AuthedWorkflowsWorkflowIdCanvasRoute
  '/workflows/$workflowId/deployments': typeof AuthedWorkflowsWorkflowIdDeploymentsRoute
  '/workflows/$workflowId/runs': typeof AuthedWorkflowsWorkflowIdRunsRouteWithChildren
  '/workflows/$workflowId/': typeof AuthedWorkflowsWorkflowIdIndexRoute
  '/workflows/$workflowId/runs/': typeof AuthedWorkflowsWorkflowIdRunsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/account': typeof AuthedAccountRoute
  '/api-playground': typeof AuthedApiPlaygroundRoute
  '/connections': typeof AuthedConnectionsRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/settings': typeof AuthedSettingsRoute
  '/resources/d1': typeof AuthedResourcesD1Route
  '/resources/env-vars': typeof AuthedResourcesEnvVarsRoute
  '/resources/kv': typeof AuthedResourcesKvRoute
  '/resources/r2': typeof AuthedResourcesR2Route
  '/resources': typeof AuthedResourcesIndexRoute
  '/runs': typeof AuthedRunsIndexRoute
  '/workflows': typeof AuthedWorkflowsIndexRoute
  '/workflows/$workflowId/canvas': typeof AuthedWorkflowsWorkflowIdCanvasRoute
  '/workflows/$workflowId/deployments': typeof AuthedWorkflowsWorkflowIdDeploymentsRoute
  '/workflows/$workflowId': typeof AuthedWorkflowsWorkflowIdIndexRoute
  '/workflows/$workflowId/runs': typeof AuthedWorkflowsWorkflowIdRunsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/_authed/account': typeof AuthedAccountRoute
  '/_authed/api-playground': typeof AuthedApiPlaygroundRoute
  '/_authed/connections': typeof AuthedConnectionsRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/resources/d1': typeof AuthedResourcesD1Route
  '/_authed/resources/env-vars': typeof AuthedResourcesEnvVarsRoute
  '/_authed/resources/kv': typeof AuthedResourcesKvRoute
  '/_authed/resources/r2': typeof AuthedResourcesR2Route
  '/_authed/workflows/$workflowId': typeof AuthedWorkflowsWorkflowIdRouteWithChildren
  '/_authed/resources/': typeof AuthedResourcesIndexRoute
  '/_authed/runs/': typeof AuthedRunsIndexRoute
  '/_authed/workflows/': typeof AuthedWorkflowsIndexRoute
  '/_authed/workflows/$workflowId/canvas': typeof AuthedWorkflowsWorkflowIdCanvasRoute
  '/_authed/workflows/$workflowId/deployments': typeof AuthedWorkflowsWorkflowIdDeploymentsRoute
  '/_authed/workflows/$workflowId/runs': typeof AuthedWorkflowsWorkflowIdRunsRouteWithChildren
  '/_authed/workflows/$workflowId/': typeof AuthedWorkflowsWorkflowIdIndexRoute
  '/_authed/workflows/$workflowId/runs/': typeof AuthedWorkflowsWorkflowIdRunsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/account'
    | '/api-playground'
    | '/connections'
    | '/dashboard'
    | '/settings'
    | '/resources/d1'
    | '/resources/env-vars'
    | '/resources/kv'
    | '/resources/r2'
    | '/workflows/$workflowId'
    | '/resources/'
    | '/runs/'
    | '/workflows/'
    | '/workflows/$workflowId/canvas'
    | '/workflows/$workflowId/deployments'
    | '/workflows/$workflowId/runs'
    | '/workflows/$workflowId/'
    | '/workflows/$workflowId/runs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/account'
    | '/api-playground'
    | '/connections'
    | '/dashboard'
    | '/settings'
    | '/resources/d1'
    | '/resources/env-vars'
    | '/resources/kv'
    | '/resources/r2'
    | '/resources'
    | '/runs'
    | '/workflows'
    | '/workflows/$workflowId/canvas'
    | '/workflows/$workflowId/deployments'
    | '/workflows/$workflowId'
    | '/workflows/$workflowId/runs'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/sign-in'
    | '/_authed/account'
    | '/_authed/api-playground'
    | '/_authed/connections'
    | '/_authed/dashboard'
    | '/_authed/settings'
    | '/_authed/resources/d1'
    | '/_authed/resources/env-vars'
    | '/_authed/resources/kv'
    | '/_authed/resources/r2'
    | '/_authed/workflows/$workflowId'
    | '/_authed/resources/'
    | '/_authed/runs/'
    | '/_authed/workflows/'
    | '/_authed/workflows/$workflowId/canvas'
    | '/_authed/workflows/$workflowId/deployments'
    | '/_authed/workflows/$workflowId/runs'
    | '/_authed/workflows/$workflowId/'
    | '/_authed/workflows/$workflowId/runs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/connections': {
      id: '/_authed/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof AuthedConnectionsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/api-playground': {
      id: '/_authed/api-playground'
      path: '/api-playground'
      fullPath: '/api-playground'
      preLoaderRoute: typeof AuthedApiPlaygroundRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/account': {
      id: '/_authed/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthedAccountRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/workflows/': {
      id: '/_authed/workflows/'
      path: '/workflows'
      fullPath: '/workflows/'
      preLoaderRoute: typeof AuthedWorkflowsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/runs/': {
      id: '/_authed/runs/'
      path: '/runs'
      fullPath: '/runs/'
      preLoaderRoute: typeof AuthedRunsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/resources/': {
      id: '/_authed/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof AuthedResourcesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/workflows/$workflowId': {
      id: '/_authed/workflows/$workflowId'
      path: '/workflows/$workflowId'
      fullPath: '/workflows/$workflowId'
      preLoaderRoute: typeof AuthedWorkflowsWorkflowIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/resources/r2': {
      id: '/_authed/resources/r2'
      path: '/resources/r2'
      fullPath: '/resources/r2'
      preLoaderRoute: typeof AuthedResourcesR2RouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/resources/kv': {
      id: '/_authed/resources/kv'
      path: '/resources/kv'
      fullPath: '/resources/kv'
      preLoaderRoute: typeof AuthedResourcesKvRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/resources/env-vars': {
      id: '/_authed/resources/env-vars'
      path: '/resources/env-vars'
      fullPath: '/resources/env-vars'
      preLoaderRoute: typeof AuthedResourcesEnvVarsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/resources/d1': {
      id: '/_authed/resources/d1'
      path: '/resources/d1'
      fullPath: '/resources/d1'
      preLoaderRoute: typeof AuthedResourcesD1RouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/workflows/$workflowId/': {
      id: '/_authed/workflows/$workflowId/'
      path: '/'
      fullPath: '/workflows/$workflowId/'
      preLoaderRoute: typeof AuthedWorkflowsWorkflowIdIndexRouteImport
      parentRoute: typeof AuthedWorkflowsWorkflowIdRoute
    }
    '/_authed/workflows/$workflowId/runs': {
      id: '/_authed/workflows/$workflowId/runs'
      path: '/runs'
      fullPath: '/workflows/$workflowId/runs'
      preLoaderRoute: typeof AuthedWorkflowsWorkflowIdRunsRouteImport
      parentRoute: typeof AuthedWorkflowsWorkflowIdRoute
    }
    '/_authed/workflows/$workflowId/deployments': {
      id: '/_authed/workflows/$workflowId/deployments'
      path: '/deployments'
      fullPath: '/workflows/$workflowId/deployments'
      preLoaderRoute: typeof AuthedWorkflowsWorkflowIdDeploymentsRouteImport
      parentRoute: typeof AuthedWorkflowsWorkflowIdRoute
    }
    '/_authed/workflows/$workflowId/canvas': {
      id: '/_authed/workflows/$workflowId/canvas'
      path: '/canvas'
      fullPath: '/workflows/$workflowId/canvas'
      preLoaderRoute: typeof AuthedWorkflowsWorkflowIdCanvasRouteImport
      parentRoute: typeof AuthedWorkflowsWorkflowIdRoute
    }
    '/_authed/workflows/$workflowId/runs/': {
      id: '/_authed/workflows/$workflowId/runs/'
      path: '/'
      fullPath: '/workflows/$workflowId/runs/'
      preLoaderRoute: typeof AuthedWorkflowsWorkflowIdRunsIndexRouteImport
      parentRoute: typeof AuthedWorkflowsWorkflowIdRunsRoute
    }
  }
}

interface AuthedWorkflowsWorkflowIdRunsRouteChildren {
  AuthedWorkflowsWorkflowIdRunsIndexRoute: typeof AuthedWorkflowsWorkflowIdRunsIndexRoute
}

const AuthedWorkflowsWorkflowIdRunsRouteChildren: AuthedWorkflowsWorkflowIdRunsRouteChildren =
  {
    AuthedWorkflowsWorkflowIdRunsIndexRoute:
      AuthedWorkflowsWorkflowIdRunsIndexRoute,
  }

const AuthedWorkflowsWorkflowIdRunsRouteWithChildren =
  AuthedWorkflowsWorkflowIdRunsRoute._addFileChildren(
    AuthedWorkflowsWorkflowIdRunsRouteChildren,
  )

interface AuthedWorkflowsWorkflowIdRouteChildren {
  AuthedWorkflowsWorkflowIdCanvasRoute: typeof AuthedWorkflowsWorkflowIdCanvasRoute
  AuthedWorkflowsWorkflowIdDeploymentsRoute: typeof AuthedWorkflowsWorkflowIdDeploymentsRoute
  AuthedWorkflowsWorkflowIdRunsRoute: typeof AuthedWorkflowsWorkflowIdRunsRouteWithChildren
  AuthedWorkflowsWorkflowIdIndexRoute: typeof AuthedWorkflowsWorkflowIdIndexRoute
}

const AuthedWorkflowsWorkflowIdRouteChildren: AuthedWorkflowsWorkflowIdRouteChildren =
  {
    AuthedWorkflowsWorkflowIdCanvasRoute: AuthedWorkflowsWorkflowIdCanvasRoute,
    AuthedWorkflowsWorkflowIdDeploymentsRoute:
      AuthedWorkflowsWorkflowIdDeploymentsRoute,
    AuthedWorkflowsWorkflowIdRunsRoute:
      AuthedWorkflowsWorkflowIdRunsRouteWithChildren,
    AuthedWorkflowsWorkflowIdIndexRoute: AuthedWorkflowsWorkflowIdIndexRoute,
  }

const AuthedWorkflowsWorkflowIdRouteWithChildren =
  AuthedWorkflowsWorkflowIdRoute._addFileChildren(
    AuthedWorkflowsWorkflowIdRouteChildren,
  )

interface AuthedRouteChildren {
  AuthedAccountRoute: typeof AuthedAccountRoute
  AuthedApiPlaygroundRoute: typeof AuthedApiPlaygroundRoute
  AuthedConnectionsRoute: typeof AuthedConnectionsRoute
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedResourcesD1Route: typeof AuthedResourcesD1Route
  AuthedResourcesEnvVarsRoute: typeof AuthedResourcesEnvVarsRoute
  AuthedResourcesKvRoute: typeof AuthedResourcesKvRoute
  AuthedResourcesR2Route: typeof AuthedResourcesR2Route
  AuthedWorkflowsWorkflowIdRoute: typeof AuthedWorkflowsWorkflowIdRouteWithChildren
  AuthedResourcesIndexRoute: typeof AuthedResourcesIndexRoute
  AuthedRunsIndexRoute: typeof AuthedRunsIndexRoute
  AuthedWorkflowsIndexRoute: typeof AuthedWorkflowsIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAccountRoute: AuthedAccountRoute,
  AuthedApiPlaygroundRoute: AuthedApiPlaygroundRoute,
  AuthedConnectionsRoute: AuthedConnectionsRoute,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedResourcesD1Route: AuthedResourcesD1Route,
  AuthedResourcesEnvVarsRoute: AuthedResourcesEnvVarsRoute,
  AuthedResourcesKvRoute: AuthedResourcesKvRoute,
  AuthedResourcesR2Route: AuthedResourcesR2Route,
  AuthedWorkflowsWorkflowIdRoute: AuthedWorkflowsWorkflowIdRouteWithChildren,
  AuthedResourcesIndexRoute: AuthedResourcesIndexRoute,
  AuthedRunsIndexRoute: AuthedRunsIndexRoute,
  AuthedWorkflowsIndexRoute: AuthedWorkflowsIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
