/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedConnectionsRouteImport } from './routes/_authed/connections'
import { Route as AuthedResourcesIndexRouteImport } from './routes/_authed/resources/index'
import { Route as AuthedWorkflowsWorkflowIdRouteImport } from './routes/_authed/workflows/$workflowId'
import { Route as AuthedResourcesR2RouteImport } from './routes/_authed/resources/r2'
import { Route as AuthedResourcesKvRouteImport } from './routes/_authed/resources/kv'
import { Route as AuthedResourcesD1RouteImport } from './routes/_authed/resources/d1'
import { Route as AuthedWorkflowsWorkflowIdIndexRouteImport } from './routes/_authed/workflows/$workflowId.index'
import { Route as AuthedWorkflowsWorkflowIdRunsRouteImport } from './routes/_authed/workflows/$workflowId.runs'
import { Route as AuthedWorkflowsWorkflowIdDeploymentsRouteImport } from './routes/_authed/workflows/$workflowId.deployments'
import { Route as AuthedWorkflowsWorkflowIdRunsRunIdRouteImport } from './routes/_authed/workflows/$workflowId.runs.$runId'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedConnectionsRoute = AuthedConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedResourcesIndexRoute = AuthedResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedWorkflowsWorkflowIdRoute =
  AuthedWorkflowsWorkflowIdRouteImport.update({
    id: '/workflows/$workflowId',
    path: '/workflows/$workflowId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedResourcesR2Route = AuthedResourcesR2RouteImport.update({
  id: '/resources/r2',
  path: '/resources/r2',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedResourcesKvRoute = AuthedResourcesKvRouteImport.update({
  id: '/resources/kv',
  path: '/resources/kv',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedResourcesD1Route = AuthedResourcesD1RouteImport.update({
  id: '/resources/d1',
  path: '/resources/d1',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedWorkflowsWorkflowIdIndexRoute =
  AuthedWorkflowsWorkflowIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedWorkflowsWorkflowIdRoute,
  } as any)
const AuthedWorkflowsWorkflowIdRunsRoute =
  AuthedWorkflowsWorkflowIdRunsRouteImport.update({
    id: '/runs',
    path: '/runs',
    getParentRoute: () => AuthedWorkflowsWorkflowIdRoute,
  } as any)
const AuthedWorkflowsWorkflowIdDeploymentsRoute =
  AuthedWorkflowsWorkflowIdDeploymentsRouteImport.update({
    id: '/deployments',
    path: '/deployments',
    getParentRoute: () => AuthedWorkflowsWorkflowIdRoute,
  } as any)
const AuthedWorkflowsWorkflowIdRunsRunIdRoute =
  AuthedWorkflowsWorkflowIdRunsRunIdRouteImport.update({
    id: '/$runId',
    path: '/$runId',
    getParentRoute: () => AuthedWorkflowsWorkflowIdRunsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/connections': typeof AuthedConnectionsRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/resources/d1': typeof AuthedResourcesD1Route
  '/resources/kv': typeof AuthedResourcesKvRoute
  '/resources/r2': typeof AuthedResourcesR2Route
  '/workflows/$workflowId': typeof AuthedWorkflowsWorkflowIdRouteWithChildren
  '/resources/': typeof AuthedResourcesIndexRoute
  '/workflows/$workflowId/deployments': typeof AuthedWorkflowsWorkflowIdDeploymentsRoute
  '/workflows/$workflowId/runs': typeof AuthedWorkflowsWorkflowIdRunsRouteWithChildren
  '/workflows/$workflowId/': typeof AuthedWorkflowsWorkflowIdIndexRoute
  '/workflows/$workflowId/runs/$runId': typeof AuthedWorkflowsWorkflowIdRunsRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/connections': typeof AuthedConnectionsRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/resources/d1': typeof AuthedResourcesD1Route
  '/resources/kv': typeof AuthedResourcesKvRoute
  '/resources/r2': typeof AuthedResourcesR2Route
  '/resources': typeof AuthedResourcesIndexRoute
  '/workflows/$workflowId/deployments': typeof AuthedWorkflowsWorkflowIdDeploymentsRoute
  '/workflows/$workflowId/runs': typeof AuthedWorkflowsWorkflowIdRunsRouteWithChildren
  '/workflows/$workflowId': typeof AuthedWorkflowsWorkflowIdIndexRoute
  '/workflows/$workflowId/runs/$runId': typeof AuthedWorkflowsWorkflowIdRunsRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/_authed/connections': typeof AuthedConnectionsRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/resources/d1': typeof AuthedResourcesD1Route
  '/_authed/resources/kv': typeof AuthedResourcesKvRoute
  '/_authed/resources/r2': typeof AuthedResourcesR2Route
  '/_authed/workflows/$workflowId': typeof AuthedWorkflowsWorkflowIdRouteWithChildren
  '/_authed/resources/': typeof AuthedResourcesIndexRoute
  '/_authed/workflows/$workflowId/deployments': typeof AuthedWorkflowsWorkflowIdDeploymentsRoute
  '/_authed/workflows/$workflowId/runs': typeof AuthedWorkflowsWorkflowIdRunsRouteWithChildren
  '/_authed/workflows/$workflowId/': typeof AuthedWorkflowsWorkflowIdIndexRoute
  '/_authed/workflows/$workflowId/runs/$runId': typeof AuthedWorkflowsWorkflowIdRunsRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/connections'
    | '/dashboard'
    | '/resources/d1'
    | '/resources/kv'
    | '/resources/r2'
    | '/workflows/$workflowId'
    | '/resources/'
    | '/workflows/$workflowId/deployments'
    | '/workflows/$workflowId/runs'
    | '/workflows/$workflowId/'
    | '/workflows/$workflowId/runs/$runId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/connections'
    | '/dashboard'
    | '/resources/d1'
    | '/resources/kv'
    | '/resources/r2'
    | '/resources'
    | '/workflows/$workflowId/deployments'
    | '/workflows/$workflowId/runs'
    | '/workflows/$workflowId'
    | '/workflows/$workflowId/runs/$runId'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/sign-in'
    | '/_authed/connections'
    | '/_authed/dashboard'
    | '/_authed/resources/d1'
    | '/_authed/resources/kv'
    | '/_authed/resources/r2'
    | '/_authed/workflows/$workflowId'
    | '/_authed/resources/'
    | '/_authed/workflows/$workflowId/deployments'
    | '/_authed/workflows/$workflowId/runs'
    | '/_authed/workflows/$workflowId/'
    | '/_authed/workflows/$workflowId/runs/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/connections': {
      id: '/_authed/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof AuthedConnectionsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/resources/': {
      id: '/_authed/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof AuthedResourcesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/workflows/$workflowId': {
      id: '/_authed/workflows/$workflowId'
      path: '/workflows/$workflowId'
      fullPath: '/workflows/$workflowId'
      preLoaderRoute: typeof AuthedWorkflowsWorkflowIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/resources/r2': {
      id: '/_authed/resources/r2'
      path: '/resources/r2'
      fullPath: '/resources/r2'
      preLoaderRoute: typeof AuthedResourcesR2RouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/resources/kv': {
      id: '/_authed/resources/kv'
      path: '/resources/kv'
      fullPath: '/resources/kv'
      preLoaderRoute: typeof AuthedResourcesKvRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/resources/d1': {
      id: '/_authed/resources/d1'
      path: '/resources/d1'
      fullPath: '/resources/d1'
      preLoaderRoute: typeof AuthedResourcesD1RouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/workflows/$workflowId/': {
      id: '/_authed/workflows/$workflowId/'
      path: '/'
      fullPath: '/workflows/$workflowId/'
      preLoaderRoute: typeof AuthedWorkflowsWorkflowIdIndexRouteImport
      parentRoute: typeof AuthedWorkflowsWorkflowIdRoute
    }
    '/_authed/workflows/$workflowId/runs': {
      id: '/_authed/workflows/$workflowId/runs'
      path: '/runs'
      fullPath: '/workflows/$workflowId/runs'
      preLoaderRoute: typeof AuthedWorkflowsWorkflowIdRunsRouteImport
      parentRoute: typeof AuthedWorkflowsWorkflowIdRoute
    }
    '/_authed/workflows/$workflowId/deployments': {
      id: '/_authed/workflows/$workflowId/deployments'
      path: '/deployments'
      fullPath: '/workflows/$workflowId/deployments'
      preLoaderRoute: typeof AuthedWorkflowsWorkflowIdDeploymentsRouteImport
      parentRoute: typeof AuthedWorkflowsWorkflowIdRoute
    }
    '/_authed/workflows/$workflowId/runs/$runId': {
      id: '/_authed/workflows/$workflowId/runs/$runId'
      path: '/$runId'
      fullPath: '/workflows/$workflowId/runs/$runId'
      preLoaderRoute: typeof AuthedWorkflowsWorkflowIdRunsRunIdRouteImport
      parentRoute: typeof AuthedWorkflowsWorkflowIdRunsRoute
    }
  }
}

interface AuthedWorkflowsWorkflowIdRunsRouteChildren {
  AuthedWorkflowsWorkflowIdRunsRunIdRoute: typeof AuthedWorkflowsWorkflowIdRunsRunIdRoute
}

const AuthedWorkflowsWorkflowIdRunsRouteChildren: AuthedWorkflowsWorkflowIdRunsRouteChildren =
  {
    AuthedWorkflowsWorkflowIdRunsRunIdRoute:
      AuthedWorkflowsWorkflowIdRunsRunIdRoute,
  }

const AuthedWorkflowsWorkflowIdRunsRouteWithChildren =
  AuthedWorkflowsWorkflowIdRunsRoute._addFileChildren(
    AuthedWorkflowsWorkflowIdRunsRouteChildren,
  )

interface AuthedWorkflowsWorkflowIdRouteChildren {
  AuthedWorkflowsWorkflowIdDeploymentsRoute: typeof AuthedWorkflowsWorkflowIdDeploymentsRoute
  AuthedWorkflowsWorkflowIdRunsRoute: typeof AuthedWorkflowsWorkflowIdRunsRouteWithChildren
  AuthedWorkflowsWorkflowIdIndexRoute: typeof AuthedWorkflowsWorkflowIdIndexRoute
}

const AuthedWorkflowsWorkflowIdRouteChildren: AuthedWorkflowsWorkflowIdRouteChildren =
  {
    AuthedWorkflowsWorkflowIdDeploymentsRoute:
      AuthedWorkflowsWorkflowIdDeploymentsRoute,
    AuthedWorkflowsWorkflowIdRunsRoute:
      AuthedWorkflowsWorkflowIdRunsRouteWithChildren,
    AuthedWorkflowsWorkflowIdIndexRoute: AuthedWorkflowsWorkflowIdIndexRoute,
  }

const AuthedWorkflowsWorkflowIdRouteWithChildren =
  AuthedWorkflowsWorkflowIdRoute._addFileChildren(
    AuthedWorkflowsWorkflowIdRouteChildren,
  )

interface AuthedRouteChildren {
  AuthedConnectionsRoute: typeof AuthedConnectionsRoute
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedResourcesD1Route: typeof AuthedResourcesD1Route
  AuthedResourcesKvRoute: typeof AuthedResourcesKvRoute
  AuthedResourcesR2Route: typeof AuthedResourcesR2Route
  AuthedWorkflowsWorkflowIdRoute: typeof AuthedWorkflowsWorkflowIdRouteWithChildren
  AuthedResourcesIndexRoute: typeof AuthedResourcesIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedConnectionsRoute: AuthedConnectionsRoute,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedResourcesD1Route: AuthedResourcesD1Route,
  AuthedResourcesKvRoute: AuthedResourcesKvRoute,
  AuthedResourcesR2Route: AuthedResourcesR2Route,
  AuthedWorkflowsWorkflowIdRoute: AuthedWorkflowsWorkflowIdRouteWithChildren,
  AuthedResourcesIndexRoute: AuthedResourcesIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
