/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedEnvVarsRouteImport } from './routes/_authed/env-vars'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedConnectionsRouteImport } from './routes/_authed/connections'
import { Route as AuthedApiPlaygroundRouteImport } from './routes/_authed/api-playground'
import { Route as AuthedAccountRouteImport } from './routes/_authed/account'
import { Route as AuthedWorkflowsIndexRouteImport } from './routes/_authed/workflows.index'
import { Route as AuthedRunsIndexRouteImport } from './routes/_authed/runs.index'
import { Route as AuthedWorkflowsWorkflowIdRouteImport } from './routes/_authed/workflows/$workflowId'
import { Route as AuthedRunsRunIdRouteImport } from './routes/_authed/runs.$runId'
import { Route as AuthedWorkflowsWorkflowIdIndexRouteImport } from './routes/_authed/workflows/$workflowId.index'
import { Route as AuthedWorkflowsWorkflowIdRunsRouteImport } from './routes/_authed/workflows/$workflowId.runs'
import { Route as AuthedWorkflowsWorkflowIdDeploymentsRouteImport } from './routes/_authed/workflows/$workflowId.deployments'
import { Route as AuthedWorkflowsWorkflowIdDeployRouteImport } from './routes/_authed/workflows/$workflowId.deploy'
import { Route as AuthedWorkflowsWorkflowIdCanvasRouteImport } from './routes/_authed/workflows/$workflowId.canvas'
import { Route as AuthedWorkflowsWorkflowIdRunsIndexRouteImport } from './routes/_authed/workflows/$workflowId.runs.index'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedEnvVarsRoute = AuthedEnvVarsRouteImport.update({
  id: '/env-vars',
  path: '/env-vars',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedConnectionsRoute = AuthedConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedApiPlaygroundRoute = AuthedApiPlaygroundRouteImport.update({
  id: '/api-playground',
  path: '/api-playground',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAccountRoute = AuthedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedWorkflowsIndexRoute = AuthedWorkflowsIndexRouteImport.update({
  id: '/workflows/',
  path: '/workflows/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRunsIndexRoute = AuthedRunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedWorkflowsWorkflowIdRoute =
  AuthedWorkflowsWorkflowIdRouteImport.update({
    id: '/workflows/$workflowId',
    path: '/workflows/$workflowId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedRunsRunIdRoute = AuthedRunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedWorkflowsWorkflowIdIndexRoute =
  AuthedWorkflowsWorkflowIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedWorkflowsWorkflowIdRoute,
  } as any)
const AuthedWorkflowsWorkflowIdRunsRoute =
  AuthedWorkflowsWorkflowIdRunsRouteImport.update({
    id: '/runs',
    path: '/runs',
    getParentRoute: () => AuthedWorkflowsWorkflowIdRoute,
  } as any)
const AuthedWorkflowsWorkflowIdDeploymentsRoute =
  AuthedWorkflowsWorkflowIdDeploymentsRouteImport.update({
    id: '/deployments',
    path: '/deployments',
    getParentRoute: () => AuthedWorkflowsWorkflowIdRoute,
  } as any)
const AuthedWorkflowsWorkflowIdDeployRoute =
  AuthedWorkflowsWorkflowIdDeployRouteImport.update({
    id: '/deploy',
    path: '/deploy',
    getParentRoute: () => AuthedWorkflowsWorkflowIdRoute,
  } as any)
const AuthedWorkflowsWorkflowIdCanvasRoute =
  AuthedWorkflowsWorkflowIdCanvasRouteImport.update({
    id: '/canvas',
    path: '/canvas',
    getParentRoute: () => AuthedWorkflowsWorkflowIdRoute,
  } as any)
const AuthedWorkflowsWorkflowIdRunsIndexRoute =
  AuthedWorkflowsWorkflowIdRunsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedWorkflowsWorkflowIdRunsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/account': typeof AuthedAccountRoute
  '/api-playground': typeof AuthedApiPlaygroundRoute
  '/connections': typeof AuthedConnectionsRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/env-vars': typeof AuthedEnvVarsRoute
  '/settings': typeof AuthedSettingsRoute
  '/runs/$runId': typeof AuthedRunsRunIdRoute
  '/workflows/$workflowId': typeof AuthedWorkflowsWorkflowIdRouteWithChildren
  '/runs/': typeof AuthedRunsIndexRoute
  '/workflows/': typeof AuthedWorkflowsIndexRoute
  '/workflows/$workflowId/canvas': typeof AuthedWorkflowsWorkflowIdCanvasRoute
  '/workflows/$workflowId/deploy': typeof AuthedWorkflowsWorkflowIdDeployRoute
  '/workflows/$workflowId/deployments': typeof AuthedWorkflowsWorkflowIdDeploymentsRoute
  '/workflows/$workflowId/runs': typeof AuthedWorkflowsWorkflowIdRunsRouteWithChildren
  '/workflows/$workflowId/': typeof AuthedWorkflowsWorkflowIdIndexRoute
  '/workflows/$workflowId/runs/': typeof AuthedWorkflowsWorkflowIdRunsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/account': typeof AuthedAccountRoute
  '/api-playground': typeof AuthedApiPlaygroundRoute
  '/connections': typeof AuthedConnectionsRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/env-vars': typeof AuthedEnvVarsRoute
  '/settings': typeof AuthedSettingsRoute
  '/runs/$runId': typeof AuthedRunsRunIdRoute
  '/runs': typeof AuthedRunsIndexRoute
  '/workflows': typeof AuthedWorkflowsIndexRoute
  '/workflows/$workflowId/canvas': typeof AuthedWorkflowsWorkflowIdCanvasRoute
  '/workflows/$workflowId/deploy': typeof AuthedWorkflowsWorkflowIdDeployRoute
  '/workflows/$workflowId/deployments': typeof AuthedWorkflowsWorkflowIdDeploymentsRoute
  '/workflows/$workflowId': typeof AuthedWorkflowsWorkflowIdIndexRoute
  '/workflows/$workflowId/runs': typeof AuthedWorkflowsWorkflowIdRunsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/_authed/account': typeof AuthedAccountRoute
  '/_authed/api-playground': typeof AuthedApiPlaygroundRoute
  '/_authed/connections': typeof AuthedConnectionsRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/env-vars': typeof AuthedEnvVarsRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/runs/$runId': typeof AuthedRunsRunIdRoute
  '/_authed/workflows/$workflowId': typeof AuthedWorkflowsWorkflowIdRouteWithChildren
  '/_authed/runs/': typeof AuthedRunsIndexRoute
  '/_authed/workflows/': typeof AuthedWorkflowsIndexRoute
  '/_authed/workflows/$workflowId/canvas': typeof AuthedWorkflowsWorkflowIdCanvasRoute
  '/_authed/workflows/$workflowId/deploy': typeof AuthedWorkflowsWorkflowIdDeployRoute
  '/_authed/workflows/$workflowId/deployments': typeof AuthedWorkflowsWorkflowIdDeploymentsRoute
  '/_authed/workflows/$workflowId/runs': typeof AuthedWorkflowsWorkflowIdRunsRouteWithChildren
  '/_authed/workflows/$workflowId/': typeof AuthedWorkflowsWorkflowIdIndexRoute
  '/_authed/workflows/$workflowId/runs/': typeof AuthedWorkflowsWorkflowIdRunsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/account'
    | '/api-playground'
    | '/connections'
    | '/dashboard'
    | '/env-vars'
    | '/settings'
    | '/runs/$runId'
    | '/workflows/$workflowId'
    | '/runs/'
    | '/workflows/'
    | '/workflows/$workflowId/canvas'
    | '/workflows/$workflowId/deploy'
    | '/workflows/$workflowId/deployments'
    | '/workflows/$workflowId/runs'
    | '/workflows/$workflowId/'
    | '/workflows/$workflowId/runs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/account'
    | '/api-playground'
    | '/connections'
    | '/dashboard'
    | '/env-vars'
    | '/settings'
    | '/runs/$runId'
    | '/runs'
    | '/workflows'
    | '/workflows/$workflowId/canvas'
    | '/workflows/$workflowId/deploy'
    | '/workflows/$workflowId/deployments'
    | '/workflows/$workflowId'
    | '/workflows/$workflowId/runs'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/sign-in'
    | '/_authed/account'
    | '/_authed/api-playground'
    | '/_authed/connections'
    | '/_authed/dashboard'
    | '/_authed/env-vars'
    | '/_authed/settings'
    | '/_authed/runs/$runId'
    | '/_authed/workflows/$workflowId'
    | '/_authed/runs/'
    | '/_authed/workflows/'
    | '/_authed/workflows/$workflowId/canvas'
    | '/_authed/workflows/$workflowId/deploy'
    | '/_authed/workflows/$workflowId/deployments'
    | '/_authed/workflows/$workflowId/runs'
    | '/_authed/workflows/$workflowId/'
    | '/_authed/workflows/$workflowId/runs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/env-vars': {
      id: '/_authed/env-vars'
      path: '/env-vars'
      fullPath: '/env-vars'
      preLoaderRoute: typeof AuthedEnvVarsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/connections': {
      id: '/_authed/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof AuthedConnectionsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/api-playground': {
      id: '/_authed/api-playground'
      path: '/api-playground'
      fullPath: '/api-playground'
      preLoaderRoute: typeof AuthedApiPlaygroundRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/account': {
      id: '/_authed/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthedAccountRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/workflows/': {
      id: '/_authed/workflows/'
      path: '/workflows'
      fullPath: '/workflows/'
      preLoaderRoute: typeof AuthedWorkflowsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/runs/': {
      id: '/_authed/runs/'
      path: '/runs'
      fullPath: '/runs/'
      preLoaderRoute: typeof AuthedRunsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/workflows/$workflowId': {
      id: '/_authed/workflows/$workflowId'
      path: '/workflows/$workflowId'
      fullPath: '/workflows/$workflowId'
      preLoaderRoute: typeof AuthedWorkflowsWorkflowIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/runs/$runId': {
      id: '/_authed/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof AuthedRunsRunIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/workflows/$workflowId/': {
      id: '/_authed/workflows/$workflowId/'
      path: '/'
      fullPath: '/workflows/$workflowId/'
      preLoaderRoute: typeof AuthedWorkflowsWorkflowIdIndexRouteImport
      parentRoute: typeof AuthedWorkflowsWorkflowIdRoute
    }
    '/_authed/workflows/$workflowId/runs': {
      id: '/_authed/workflows/$workflowId/runs'
      path: '/runs'
      fullPath: '/workflows/$workflowId/runs'
      preLoaderRoute: typeof AuthedWorkflowsWorkflowIdRunsRouteImport
      parentRoute: typeof AuthedWorkflowsWorkflowIdRoute
    }
    '/_authed/workflows/$workflowId/deployments': {
      id: '/_authed/workflows/$workflowId/deployments'
      path: '/deployments'
      fullPath: '/workflows/$workflowId/deployments'
      preLoaderRoute: typeof AuthedWorkflowsWorkflowIdDeploymentsRouteImport
      parentRoute: typeof AuthedWorkflowsWorkflowIdRoute
    }
    '/_authed/workflows/$workflowId/deploy': {
      id: '/_authed/workflows/$workflowId/deploy'
      path: '/deploy'
      fullPath: '/workflows/$workflowId/deploy'
      preLoaderRoute: typeof AuthedWorkflowsWorkflowIdDeployRouteImport
      parentRoute: typeof AuthedWorkflowsWorkflowIdRoute
    }
    '/_authed/workflows/$workflowId/canvas': {
      id: '/_authed/workflows/$workflowId/canvas'
      path: '/canvas'
      fullPath: '/workflows/$workflowId/canvas'
      preLoaderRoute: typeof AuthedWorkflowsWorkflowIdCanvasRouteImport
      parentRoute: typeof AuthedWorkflowsWorkflowIdRoute
    }
    '/_authed/workflows/$workflowId/runs/': {
      id: '/_authed/workflows/$workflowId/runs/'
      path: '/'
      fullPath: '/workflows/$workflowId/runs/'
      preLoaderRoute: typeof AuthedWorkflowsWorkflowIdRunsIndexRouteImport
      parentRoute: typeof AuthedWorkflowsWorkflowIdRunsRoute
    }
  }
}

interface AuthedWorkflowsWorkflowIdRunsRouteChildren {
  AuthedWorkflowsWorkflowIdRunsIndexRoute: typeof AuthedWorkflowsWorkflowIdRunsIndexRoute
}

const AuthedWorkflowsWorkflowIdRunsRouteChildren: AuthedWorkflowsWorkflowIdRunsRouteChildren =
  {
    AuthedWorkflowsWorkflowIdRunsIndexRoute:
      AuthedWorkflowsWorkflowIdRunsIndexRoute,
  }

const AuthedWorkflowsWorkflowIdRunsRouteWithChildren =
  AuthedWorkflowsWorkflowIdRunsRoute._addFileChildren(
    AuthedWorkflowsWorkflowIdRunsRouteChildren,
  )

interface AuthedWorkflowsWorkflowIdRouteChildren {
  AuthedWorkflowsWorkflowIdCanvasRoute: typeof AuthedWorkflowsWorkflowIdCanvasRoute
  AuthedWorkflowsWorkflowIdDeployRoute: typeof AuthedWorkflowsWorkflowIdDeployRoute
  AuthedWorkflowsWorkflowIdDeploymentsRoute: typeof AuthedWorkflowsWorkflowIdDeploymentsRoute
  AuthedWorkflowsWorkflowIdRunsRoute: typeof AuthedWorkflowsWorkflowIdRunsRouteWithChildren
  AuthedWorkflowsWorkflowIdIndexRoute: typeof AuthedWorkflowsWorkflowIdIndexRoute
}

const AuthedWorkflowsWorkflowIdRouteChildren: AuthedWorkflowsWorkflowIdRouteChildren =
  {
    AuthedWorkflowsWorkflowIdCanvasRoute: AuthedWorkflowsWorkflowIdCanvasRoute,
    AuthedWorkflowsWorkflowIdDeployRoute: AuthedWorkflowsWorkflowIdDeployRoute,
    AuthedWorkflowsWorkflowIdDeploymentsRoute:
      AuthedWorkflowsWorkflowIdDeploymentsRoute,
    AuthedWorkflowsWorkflowIdRunsRoute:
      AuthedWorkflowsWorkflowIdRunsRouteWithChildren,
    AuthedWorkflowsWorkflowIdIndexRoute: AuthedWorkflowsWorkflowIdIndexRoute,
  }

const AuthedWorkflowsWorkflowIdRouteWithChildren =
  AuthedWorkflowsWorkflowIdRoute._addFileChildren(
    AuthedWorkflowsWorkflowIdRouteChildren,
  )

interface AuthedRouteChildren {
  AuthedAccountRoute: typeof AuthedAccountRoute
  AuthedApiPlaygroundRoute: typeof AuthedApiPlaygroundRoute
  AuthedConnectionsRoute: typeof AuthedConnectionsRoute
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedEnvVarsRoute: typeof AuthedEnvVarsRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedRunsRunIdRoute: typeof AuthedRunsRunIdRoute
  AuthedWorkflowsWorkflowIdRoute: typeof AuthedWorkflowsWorkflowIdRouteWithChildren
  AuthedRunsIndexRoute: typeof AuthedRunsIndexRoute
  AuthedWorkflowsIndexRoute: typeof AuthedWorkflowsIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAccountRoute: AuthedAccountRoute,
  AuthedApiPlaygroundRoute: AuthedApiPlaygroundRoute,
  AuthedConnectionsRoute: AuthedConnectionsRoute,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedEnvVarsRoute: AuthedEnvVarsRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedRunsRunIdRoute: AuthedRunsRunIdRoute,
  AuthedWorkflowsWorkflowIdRoute: AuthedWorkflowsWorkflowIdRouteWithChildren,
  AuthedRunsIndexRoute: AuthedRunsIndexRoute,
  AuthedWorkflowsIndexRoute: AuthedWorkflowsIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
