// Renders all React-email templates to static HTML with placeholder tokens
// at build time. The runtime package then does pure string substitution —
// no react-dom/server at runtime, so the renderer works identically on Node
// and Cloudflare Workers (and any other JS runtime).
//
// Placeholder convention: `__VAR_NAME__`. We pass template props as literal
// placeholder strings through React, so the rendered HTML contains those
// tokens verbatim, ready for a simple .replaceAll() at runtime.

import { render } from '@react-email/components'
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { createElement } from 'react'
import { MagicLinkEmail } from '../src/templates/magic-link.js'

const __dirname = dirname(fileURLToPath(import.meta.url))
const outDir = resolve(__dirname, '../src/templates/__generated__')
mkdirSync(outDir, { recursive: true })

function fileHeader(name: string) {
  return `// GENERATED by packages/email/scripts/prerender.ts — do not edit.\n// Source: src/templates/${name}.tsx\n\n`
}

async function renderTemplate<P extends Record<string, string>>(
  component: (props: P) => JSX.Element,
  placeholders: P,
  outName: string,
  constName: string,
) {
  const html = await render(createElement(component, placeholders))
  const body = `${fileHeader(outName)}export const ${constName}_HTML = ${JSON.stringify(html)}\n`
  writeFileSync(resolve(outDir, `${outName}.ts`), body)
  console.log(`[prerender] wrote ${outName}.ts (${html.length} bytes)`)
}

await renderTemplate(
  MagicLinkEmail as never,
  {
    url: '__MAGIC_LINK_URL__',
    appName: '__APP_NAME__',
    appUrl: '__APP_URL__',
  },
  'magic-link',
  'MAGIC_LINK',
)

console.log('[prerender] done')
