type HttpMethod = 'GET' | 'POST' | 'PATCH' | 'DELETE'
type Scope = 'read' | 'write' | 'deploy'

export interface EndpointParam {
  name: string
  in: 'path' | 'query'
  required: boolean
}

export interface EndpointDef {
  id: string
  group: string
  method: HttpMethod
  path: string
  label: string
  scope: Scope
  params: EndpointParam[]
  hasBody: boolean
  bodyExample?: string
}

export const endpoints: EndpointDef[] = [
  // Workflows
  {
    id: 'list-workflows',
    group: 'Workflows',
    method: 'GET',
    path: '/api/workflows',
    label: 'List workflows',
    scope: 'read',
    params: [],
    hasBody: false,
  },
  {
    id: 'get-workflow',
    group: 'Workflows',
    method: 'GET',
    path: '/api/workflows/:id',
    label: 'Get workflow',
    scope: 'read',
    params: [{ name: 'id', in: 'path', required: true }],
    hasBody: false,
  },
  {
    id: 'get-workflow-full',
    group: 'Workflows',
    method: 'GET',
    path: '/api/workflows/:id/full',
    label: 'Get workflow (full)',
    scope: 'read',
    params: [
      { name: 'id', in: 'path', required: true },
      { name: 'version', in: 'query', required: false },
    ],
    hasBody: false,
  },
  {
    id: 'create-workflow',
    group: 'Workflows',
    method: 'POST',
    path: '/api/workflows',
    label: 'Create workflow',
    scope: 'write',
    params: [],
    hasBody: true,
    bodyExample: JSON.stringify({ name: 'My Workflow', description: '' }, null, 2),
  },
  {
    id: 'update-workflow',
    group: 'Workflows',
    method: 'PATCH',
    path: '/api/workflows/:id',
    label: 'Update workflow',
    scope: 'write',
    params: [{ name: 'id', in: 'path', required: true }],
    hasBody: true,
    bodyExample: JSON.stringify({ name: 'Updated Name' }, null, 2),
  },
  {
    id: 'move-workflow',
    group: 'Workflows',
    method: 'PATCH',
    path: '/api/workflows/:id/move',
    label: 'Move workflow to project',
    scope: 'write',
    params: [{ name: 'id', in: 'path', required: true }],
    hasBody: true,
    bodyExample: JSON.stringify({ targetProjectId: '' }, null, 2),
  },
  {
    id: 'delete-workflow',
    group: 'Workflows',
    method: 'DELETE',
    path: '/api/workflows/:id',
    label: 'Delete workflow',
    scope: 'write',
    params: [{ name: 'id', in: 'path', required: true }],
    hasBody: false,
  },

  // Projects
  {
    id: 'list-projects',
    group: 'Projects',
    method: 'GET',
    path: '/api/projects',
    label: 'List projects',
    scope: 'read',
    params: [],
    hasBody: false,
  },
  {
    id: 'create-project',
    group: 'Projects',
    method: 'POST',
    path: '/api/projects',
    label: 'Create project',
    scope: 'write',
    params: [],
    hasBody: true,
    bodyExample: JSON.stringify(
      { name: 'My Project', slug: 'my-project', description: '' },
      null,
      2,
    ),
  },
  {
    id: 'update-project',
    group: 'Projects',
    method: 'PATCH',
    path: '/api/projects/:id',
    label: 'Update project',
    scope: 'write',
    params: [{ name: 'id', in: 'path', required: true }],
    hasBody: true,
    bodyExample: JSON.stringify({ name: 'Updated Name' }, null, 2),
  },
  {
    id: 'delete-project',
    group: 'Projects',
    method: 'DELETE',
    path: '/api/projects/:id',
    label: 'Delete project',
    scope: 'write',
    params: [{ name: 'id', in: 'path', required: true }],
    hasBody: false,
  },

  // Versions
  {
    id: 'list-versions',
    group: 'Versions',
    method: 'GET',
    path: '/api/workflows/:workflowId/versions',
    label: 'List versions',
    scope: 'read',
    params: [{ name: 'workflowId', in: 'path', required: true }],
    hasBody: false,
  },
  {
    id: 'get-version',
    group: 'Versions',
    method: 'GET',
    path: '/api/workflows/:workflowId/versions/:versionId',
    label: 'Get version',
    scope: 'read',
    params: [
      { name: 'workflowId', in: 'path', required: true },
      { name: 'versionId', in: 'path', required: true },
    ],
    hasBody: false,
  },
  {
    id: 'create-version',
    group: 'Versions',
    method: 'POST',
    path: '/api/workflows/:workflowId/versions',
    label: 'Create version',
    scope: 'write',
    params: [{ name: 'workflowId', in: 'path', required: true }],
    hasBody: true,
    bodyExample: JSON.stringify({ ir: {} }, null, 2),
  },
  {
    id: 'lock-version',
    group: 'Versions',
    method: 'PATCH',
    path: '/api/workflows/:workflowId/versions/:versionId',
    label: 'Lock/unlock version',
    scope: 'write',
    params: [
      { name: 'workflowId', in: 'path', required: true },
      { name: 'versionId', in: 'path', required: true },
    ],
    hasBody: true,
    bodyExample: JSON.stringify({ locked: true }, null, 2),
  },
  {
    id: 'revert-version',
    group: 'Versions',
    method: 'POST',
    path: '/api/workflows/:workflowId/versions/:versionId/revert',
    label: 'Revert to version',
    scope: 'write',
    params: [
      { name: 'workflowId', in: 'path', required: true },
      { name: 'versionId', in: 'path', required: true },
    ],
    hasBody: false,
  },
  {
    id: 'delete-version',
    group: 'Versions',
    method: 'DELETE',
    path: '/api/workflows/:workflowId/versions/:versionId',
    label: 'Delete version',
    scope: 'write',
    params: [
      { name: 'workflowId', in: 'path', required: true },
      { name: 'versionId', in: 'path', required: true },
    ],
    hasBody: false,
  },

  // Deployments
  {
    id: 'list-all-deployments',
    group: 'Deployments',
    method: 'GET',
    path: '/api/deployments',
    label: 'List all deployments',
    scope: 'read',
    params: [],
    hasBody: false,
  },
  {
    id: 'list-workflow-deployments',
    group: 'Deployments',
    method: 'GET',
    path: '/api/workflows/:workflowId/deployments',
    label: 'List workflow deployments',
    scope: 'read',
    params: [{ name: 'workflowId', in: 'path', required: true }],
    hasBody: false,
  },
  {
    id: 'deploy-workflow',
    group: 'Deployments',
    method: 'POST',
    path: '/api/workflows/:workflowId/deploy',
    label: 'Deploy workflow',
    scope: 'deploy',
    params: [{ name: 'workflowId', in: 'path', required: true }],
    hasBody: true,
    bodyExample: JSON.stringify({ connectionId: '', versionId: '' }, null, 2),
  },
  {
    id: 'trigger-workflow',
    group: 'Deployments',
    method: 'POST',
    path: '/api/workflows/:workflowId/trigger',
    label: 'Trigger workflow',
    scope: 'deploy',
    params: [{ name: 'workflowId', in: 'path', required: true }],
    hasBody: true,
    bodyExample: JSON.stringify({ connectionId: '', params: {} }, null, 2),
  },
  {
    id: 'takedown-workflow',
    group: 'Deployments',
    method: 'POST',
    path: '/api/workflows/:workflowId/takedown',
    label: 'Takedown deployment',
    scope: 'deploy',
    params: [{ name: 'workflowId', in: 'path', required: true }],
    hasBody: true,
    bodyExample: JSON.stringify({ connectionId: '' }, null, 2),
  },
  // Runs
  {
    id: 'list-all-runs',
    group: 'Runs',
    method: 'GET',
    path: '/api/runs',
    label: 'List all runs',
    scope: 'read',
    params: [],
    hasBody: false,
  },
  {
    id: 'list-workflow-runs',
    group: 'Runs',
    method: 'GET',
    path: '/api/workflows/:workflowId/runs',
    label: 'List workflow runs',
    scope: 'read',
    params: [{ name: 'workflowId', in: 'path', required: true }],
    hasBody: false,
  },
  {
    id: 'get-run',
    group: 'Runs',
    method: 'GET',
    path: '/api/workflows/:workflowId/runs/:runId',
    label: 'Get run',
    scope: 'read',
    params: [
      { name: 'workflowId', in: 'path', required: true },
      { name: 'runId', in: 'path', required: true },
    ],
    hasBody: false,
  },
  {
    id: 'pause-run',
    group: 'Runs',
    method: 'POST',
    path: '/api/workflows/:workflowId/runs/:runId/pause',
    label: 'Pause run',
    scope: 'deploy',
    params: [
      { name: 'workflowId', in: 'path', required: true },
      { name: 'runId', in: 'path', required: true },
    ],
    hasBody: false,
  },
  {
    id: 'resume-run',
    group: 'Runs',
    method: 'POST',
    path: '/api/workflows/:workflowId/runs/:runId/resume',
    label: 'Resume run',
    scope: 'deploy',
    params: [
      { name: 'workflowId', in: 'path', required: true },
      { name: 'runId', in: 'path', required: true },
    ],
    hasBody: false,
  },
  {
    id: 'terminate-run',
    group: 'Runs',
    method: 'POST',
    path: '/api/workflows/:workflowId/runs/:runId/terminate',
    label: 'Terminate run',
    scope: 'deploy',
    params: [
      { name: 'workflowId', in: 'path', required: true },
      { name: 'runId', in: 'path', required: true },
    ],
    hasBody: false,
  },

  // Connections
  {
    id: 'list-connections',
    group: 'Connections',
    method: 'GET',
    path: '/api/connections',
    label: 'List connections',
    scope: 'read',
    params: [],
    hasBody: false,
  },
  {
    id: 'create-connection',
    group: 'Connections',
    method: 'POST',
    path: '/api/connections',
    label: 'Create connection',
    scope: 'write',
    params: [],
    hasBody: true,
    bodyExample: JSON.stringify(
      {
        provider: 'cloudflare',
        credentials: { apiToken: '', accountId: '' },
        name: 'My Connection',
      },
      null,
      2,
    ),
  },
  {
    id: 'update-connection',
    group: 'Connections',
    method: 'PATCH',
    path: '/api/connections/:id',
    label: 'Update connection',
    scope: 'write',
    params: [{ name: 'id', in: 'path', required: true }],
    hasBody: true,
    bodyExample: JSON.stringify({ name: 'Updated Name' }, null, 2),
  },
  {
    id: 'delete-connection',
    group: 'Connections',
    method: 'DELETE',
    path: '/api/connections/:id',
    label: 'Delete connection',
    scope: 'write',
    params: [{ name: 'id', in: 'path', required: true }],
    hasBody: false,
  },

  // Environment Variables
  {
    id: 'list-env-vars',
    group: 'Environment Variables',
    method: 'GET',
    path: '/api/env-vars',
    label: 'List environment variables',
    scope: 'read',
    params: [],
    hasBody: false,
  },
  {
    id: 'create-env-var',
    group: 'Environment Variables',
    method: 'POST',
    path: '/api/env-vars',
    label: 'Create environment variable',
    scope: 'write',
    params: [],
    hasBody: true,
    bodyExample: JSON.stringify({ name: 'MY_VAR', value: 'my-value', isSecret: false }, null, 2),
  },
  {
    id: 'update-env-var',
    group: 'Environment Variables',
    method: 'PATCH',
    path: '/api/env-vars/:id',
    label: 'Update environment variable',
    scope: 'write',
    params: [{ name: 'id', in: 'path', required: true }],
    hasBody: true,
    bodyExample: JSON.stringify({ value: 'new-value' }, null, 2),
  },
  {
    id: 'delete-env-var',
    group: 'Environment Variables',
    method: 'DELETE',
    path: '/api/env-vars/:id',
    label: 'Delete environment variable',
    scope: 'write',
    params: [{ name: 'id', in: 'path', required: true }],
    hasBody: false,
  },

  // Resources
  {
    id: 'list-kv-namespaces',
    group: 'Resources',
    method: 'GET',
    path: '/api/resources/kv/namespaces',
    label: 'List KV namespaces',
    scope: 'read',
    params: [{ name: 'connectionId', in: 'query', required: true }],
    hasBody: false,
  },
  {
    id: 'list-kv-keys',
    group: 'Resources',
    method: 'GET',
    path: '/api/resources/kv/namespaces/:namespaceId/keys',
    label: 'List KV keys',
    scope: 'read',
    params: [
      { name: 'namespaceId', in: 'path', required: true },
      { name: 'connectionId', in: 'query', required: true },
      { name: 'prefix', in: 'query', required: false },
      { name: 'cursor', in: 'query', required: false },
      { name: 'limit', in: 'query', required: false },
    ],
    hasBody: false,
  },
  {
    id: 'get-kv-value',
    group: 'Resources',
    method: 'GET',
    path: '/api/resources/kv/namespaces/:namespaceId/values/:key',
    label: 'Get KV value',
    scope: 'read',
    params: [
      { name: 'namespaceId', in: 'path', required: true },
      { name: 'key', in: 'path', required: true },
      { name: 'connectionId', in: 'query', required: true },
    ],
    hasBody: false,
  },
  {
    id: 'list-d1-databases',
    group: 'Resources',
    method: 'GET',
    path: '/api/resources/d1/databases',
    label: 'List D1 databases',
    scope: 'read',
    params: [{ name: 'connectionId', in: 'query', required: true }],
    hasBody: false,
  },
  {
    id: 'query-d1',
    group: 'Resources',
    method: 'POST',
    path: '/api/resources/d1/databases/:databaseId/query',
    label: 'Query D1 database',
    scope: 'read',
    params: [{ name: 'databaseId', in: 'path', required: true }],
    hasBody: true,
    bodyExample: JSON.stringify({ connectionId: '', sql: 'SELECT 1', params: [] }, null, 2),
  },
  {
    id: 'list-r2-buckets',
    group: 'Resources',
    method: 'GET',
    path: '/api/resources/r2/buckets',
    label: 'List R2 buckets',
    scope: 'read',
    params: [{ name: 'connectionId', in: 'query', required: true }],
    hasBody: false,
  },
  {
    id: 'list-r2-objects',
    group: 'Resources',
    method: 'GET',
    path: '/api/resources/r2/buckets/:bucketName/objects',
    label: 'List R2 objects',
    scope: 'read',
    params: [
      { name: 'bucketName', in: 'path', required: true },
      { name: 'connectionId', in: 'query', required: true },
      { name: 'prefix', in: 'query', required: false },
      { name: 'cursor', in: 'query', required: false },
      { name: 'limit', in: 'query', required: false },
    ],
    hasBody: false,
  },

  // Nodes
  {
    id: 'list-nodes',
    group: 'Nodes',
    method: 'GET',
    path: '/api/nodes',
    label: 'List all nodes',
    scope: 'read',
    params: [],
    hasBody: false,
  },
  {
    id: 'get-node-templates',
    group: 'Nodes',
    method: 'GET',
    path: '/api/nodes/templates',
    label: 'Get node templates',
    scope: 'read',
    params: [],
    hasBody: false,
  },
  {
    id: 'get-node',
    group: 'Nodes',
    method: 'GET',
    path: '/api/nodes/:nodeId',
    label: 'Get node definition',
    scope: 'read',
    params: [{ name: 'nodeId', in: 'path', required: true }],
    hasBody: false,
  },

  // Marketplace
  {
    id: 'browse-marketplace',
    group: 'Marketplace',
    method: 'GET',
    path: '/api/marketplace',
    label: 'Browse marketplace',
    scope: 'read',
    params: [],
    hasBody: false,
  },
  {
    id: 'get-marketplace-node',
    group: 'Marketplace',
    method: 'GET',
    path: '/api/marketplace/:nodeId',
    label: 'Get marketplace node',
    scope: 'read',
    params: [{ name: 'nodeId', in: 'path', required: true }],
    hasBody: false,
  },
  {
    id: 'install-node',
    group: 'Marketplace',
    method: 'POST',
    path: '/api/marketplace/install',
    label: 'Install node',
    scope: 'write',
    params: [],
    hasBody: true,
    bodyExample: JSON.stringify({ nodeId: 'resend_send_email', version: '0.0.1' }, null, 2),
  },
  {
    id: 'uninstall-node',
    group: 'Marketplace',
    method: 'POST',
    path: '/api/marketplace/uninstall',
    label: 'Uninstall node',
    scope: 'write',
    params: [],
    hasBody: true,
    bodyExample: JSON.stringify({ nodeId: 'resend_send_email' }, null, 2),
  },
  {
    id: 'update-node',
    group: 'Marketplace',
    method: 'POST',
    path: '/api/marketplace/update',
    label: 'Update node',
    scope: 'write',
    params: [],
    hasBody: true,
    bodyExample: JSON.stringify({ nodeId: 'resend_send_email', version: '0.0.2' }, null, 2),
  },
  {
    id: 'list-installed-nodes',
    group: 'Marketplace',
    method: 'GET',
    path: '/api/marketplace/installed',
    label: 'List installed nodes',
    scope: 'read',
    params: [],
    hasBody: false,
  },
]

export const endpointGroups = [...new Set(endpoints.map((e) => e.group))]
